site_name: RSC Codex
site_url: https://aeravel.github.io/pa/
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
nav:
  - Главная: index.md
extra_css:
  - assets/stylesheets/landing.css
extra_javascript:
  - assets/javascripts/landing.js
